spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  type-enums-package: com.dzl.blog2.enums

blog:
  global:
    secret: default
    expire: 2592000
    alreadySetup: true
    mock: true


# Logger Config
logging:
  level:
    com.dzl.blog2: debug